# Change these first
owner: otakuemily # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Kemonoforge
    url: https://forge.kemonomimi.moe

  - name: Kemonotrix
    url: https://matrix.kemonomimi.moe

  - name: Kemonosocial
    url: https://social.kemonomimi.moe

  - name: Kemonolink
    url: https://link.kemonomimi.moe
    
status-website:
  cname: uptime.kemonomimi.moe
  logoUrl: https://raw.githubusercontent.com/OtakuEmily/uptime/refs/heads/master/assets/upptime-icon.svg
  name: Kemonomimi.moe
  introTitle: "Kemonomimi.moe Uptime"
  introMessage: Our Github-powered uptime page!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
