# Change these first
owner: otakuemily # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Kemonoforge
    url: https://forge.kemonomimi.moe

  - name: Kemonotrix
    url: https://matrix.kemonomimi.moe

  - name: Kemonosocial
    url: https://social.kemonomimi.moe

  - name: Kemonolink
    url: https://link.kemonomimi.moe
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Kemonomimi.moe
  introTitle: "Kemonomimi.moe Uptime"
  introMessage: Our Github-powered uptime page!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
